server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://54.180.93.206:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devit_payment?serverTimezone=Asia/Seoul
    username: devit
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    password: 1234
    port: 5672
    username: devit
    exchange: x.devit.point_user
    queue: q.devit.point_user
    routingkey: devit.routingkey

  application:
    name: certification-service

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # jwt secret key
jwt:
  secret: '50g/NGsxw15SwkKw8f+fxuXw6hBrEVYXCgJwyzItp8I='
