server:
  port: 8080

logging:
  level:
    root: info
  file:
    name: /home/ubuntu/log/application-debug.log

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://54.180.93.206:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-devit-payment.copkmnpqtze8.ap-northeast-2.rds.amazonaws.com:3306/devit_payment?serverTimezone=Asia/Seoul
    username: dahye
    password: dlekgp0912!!
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 52.79.236.81
    password: 1234
    port: 5672
    username: devit
    exchange: x.devit.point_user
    queue: q.devit.point_user
    routingkey: devit.routingkey

  application:
    name: payment-service

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  # jwt secret key
jwt:
  secret: '50g/NGsxw15SwkKw8f+fxuXw6hBrEVYXCgJwyzItp8I='
